<?xml version="1.0" encoding="utf-8"?><Database Name="QL_SINHVIEN" Class="QL_SinhVienDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-C9G1193L\SQL_SERVER_HANG;Initial Catalog=QL_SINHVIEN;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QL_SINHVIENConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SINHVIEN" Member="SINHVIENs">
    <Type Name="SINHVIEN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>